### PR TITLE
Adds modal version with bootstrap without jquery

### PR DESCRIPTION
**Pull request by luanfreitasdev**
This PR supports using the **bootstrap** package in version **4.6** and **5** without using **Jquery**.

Some changes were made in the Modal component and in the modal.js file and also in the tests to be able to call 3 variables that bootstrap controls.

By default I put a configuration file for the user to select the css framework of their choice, but tailwind will be loaded without configuration.

### CODE REVIEW

**Comment by PhiloNL** [comment]
Hi @luanfreitasdev,
Thanks for the PR but for now I'm only supporting Tailwind CSS (https://github.com/livewire-ui/modal/issues/23).
In the future, I might add a non-CSS framework version depending on demand.

**Comment by kevin4dhd** [comment]
Any advance? i really need this

**Comment by PhiloNL** [comment]
@kevin4dhd feel free to fork this repository and create a Bootstrap / jQuery version.

**Comment by Restingo** [comment]
@luanfreitasdev do you've got a working fork?

**Comment by luanfreitasdev** [comment]
@Restingo 

Hi, there's this branch, see if it works please

https://github.com/luanfreitasdev/modal/tree/feature/bs-modal

 Thank you

**Comment by Restingo** [comment]
@luanfreitasdev I'm getting the following error:

```
Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at modal.js:1
    at ge (cdn.min.js:5)
    at cdn.min.js:5
```

**Comment by luanfreitasdev** [comment]
@Restingo 

did you put modal.js from that same repo? 

You will have to manually put and clear the cache

**Comment by Restingo** [comment]
@luanfreitasdev yes I'm using the same files and also cleared local and browser caches.

**Comment by Restingo** [comment]
@luanfreitasdev I've added `x-ref="{{ $id }}"` to `bootstrap.blade.php` like the following, now the error is gone:

```
<div
    id="{{ $id }}"
    x-ref="{{ $id }}"
    class="modal fade" tabindex="-1" role="dialog"
    aria-hidden="true"
>
```

Can you please check? But there is also stuff like `x-show.immediate="activeComponent == '{{ $id }}'"` missing?

**Comment by Restingo** [comment]
@luanfreitasdev also when I'm closing the modal with **ESC** or **X** the gray background still stays and needs another **ESC** to hide.

**Comment by Restingo** [comment]
@luanfreitasdev any news?

**Comment by RishabSwift** [comment]
@luanfreitasdev Thanks for this.
We've been using for production with some minor tweaks. It would be great if this pull request was accepted and supported with the official package.

**Comment by luanfreitasdev** [comment]
Thanks @RishabSwift, @Restingo  ,

I redid the installation in a new project and it worked perfectly without needing to change anything.

**Comment by RishabSwift** [comment]
@luanfreitasdev, some minor bugs I have noticed
- When you have a child modal with a different width set through `bsModalWidth()`, then it does not work as expected. For example, if the parent width is `lg` and the child width is `sm`, then the child's class becomes `modal-lg modal-sm` (notice the parent modal's class gets carried over to the child modal). 
- When you open a child modal and dismiss it, the modal is dismissed but backdrop drop of the child modal remains. You have to press `esc` to remove the backdrop. For example, if you open a parent modal, and open a child modal, then dismiss the child modal, then open the child modal again, you have to press `esc` twice to dismiss it. I think this is what @Restingo is referring to.

**Comment by luanfreitasdev** [comment]
Hello, @RishabSwift 

what changes did you need to make to make this part work, can you share with us?

Thank you!

**Comment by invaders-xx** [comment]
@luanfreitasdev ,

How can I install your fork ?

Many thanks in advance for your feedback.

**Comment by umahatokula** [comment]
> @luanfreitasdev ,
> 
> How can I install your fork ?
> 
> Many thanks in advance for your feedback.

Were you able to install this? I need it too

**Comment by madurapa** [comment]
For anyone interested in installing this version via composer, follow the steps below

Add the package to your composer under **require** section 

`"livewire-ui/modal": "dev-feature/bs-modal",`

Then add this new value as the composer's new root value
```
,
  "repositories": [
    {
      "type": "vcs",
      "url": "git@github.com:luanfreitasdev/modal.git"
    }
  ]
```

Then run `composer update`

You will ask for a token from GitHub if you add this for the first time, visit the link which gave in the terminal and get the token.

**Comment by almiro75** [comment]
composer update
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.6) does not satisfy that requirement.
    - Root composer.json requires laravel/ui ^4.0 -> satisfiable by laravel/ui[v4.0.0, v4.0.1, v4.0.2, 4.x-dev].
    - Conclusion: don't install laravel/framework v9.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.22.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.22.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.23.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.24.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.25.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.25.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.26.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.26.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.27.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.28.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.29.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.30.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.30.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.31.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.32.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.33.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.34.0 (conflict analysis result)
    - livewire-ui/modal dev-feature/bs-modal requires livewire-ui/livewire-ui ^0.1.0 -> satisfiable by livewire-ui/livewire-ui[0.1.0].
    - Root composer.json requires livewire-ui/modal dev-feature/bs-modal -> satisfiable by livewire-ui/modal[dev-feature/bs-modal].
    - Conclusion: don't install laravel/framework v9.19.0 (conflict analysis result)
    - livewire-ui/livewire-ui 0.1.0 requires illuminate/support ^8.0 -> satisfiable by illuminate/support[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.19.0, ..., 9.x-dev]. laravel/framework replaces illumi
nate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.19 -> satisfiable by laravel/framework[v9.19.0, ..., 9.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by PhiloNL** [comment]
The [Pro version](https://wire-elements.dev/pro) includes a modal and slide-over that work with Bootstrap but does require Alpine.

**Pull request closed without merging**
